### ISSUE TITLE
KODI  Support  Add-on Support  Video Add-ons  The official addon DR TV (drnu) byTWinther has stopped working

### ISSUE THREAD

**Issue by krogsbell** [twinther/script.module.buggalo#7]
The addon DR TV (drnu) has started failing on archives.
The reason is that DR.DK has changed links from visible to encrypted links.
The addon points to https://tommy.winther.nu/wordpress/ to get support, but this site do not accept support requests.

As an example the following link still works (in Denmark)
https://drod01s-vh.akamaihd.net/i/dk/cle...dOfHearing

But after 2019-01-29 11:18:20 the link in the DR TV addon has changed to:
"Uri":null,"EncryptedUri":"01000003002a56fa396c55f053ca24aac5fff9fc4a75265083b55a7c3eb2c24dca13bcb19b5412a7564ed0c44cdd04fb4c357261790e1b3aae4fcdb324f10404152d202ab66e591a26e6bb08c2064a7f14ea2608276d880a44cf81fd4766cb5898f9e04db723cd463bccaffcb2d2847ef14980d35797627a357938b30a80dbd61ca5c2c63cb17a34f71798e33b06412d0158123d107ab99177856002275ab0675a2354c2ce6c5cc83c73fdb358547c2353a165a4d505559dc8468363aa93e8cbedf83a0d3a6cfbbc10e939fe187ff66407051175165d38a4a514e5cb3e3e480c58402a8fefcebd14f601463d9dd0cfdfddaba89221e2c938c4409026ea99090bd2d3661537a3927973a6ba07c0b42688074d04abea02a68d02b88ea66f99327805959338077011b334f6547fbbdc742cc62dbee24b7ef7f309e6c8e8da6f92463939f8b71e96171ae1dbd5232b66b741fbd749d4c36e9210cae7f7d0e33d3d81039abb035cc676ec773332eef73072b2cc9892ef66a03ab50d23109a184d82cc26f58fd19b05f0502d98e225edc175cb59838bdc06","FileFormat":"mp4","Target":"HLS"

This is just an information to tell about my information on this problem.

**Comment by twinther** [comment]
Only official partners knows how to decrypt the URI, so nothing I can do.
https://tommy.winther.nu/wordpress/2019/01/30/dr-tv-addon/
